CREATE TABLE IF NOT EXISTS users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL,
    user_name VARCHAR(255),
    birthday DATE
);

CREATE TABLE IF NOT EXISTS films (
    film_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    mpa_id INT,
    releasedate DATE,
    duration INT,
    rate INT
);

CREATE TABLE IF NOT EXISTS user_films (
    user_id INT REFERENCES users(user_id) ON DELETE CASCADE,
    film_id INT REFERENCES films(film_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS user_friends (
    userone_id INT REFERENCES users(user_id) ON DELETE CASCADE,
    usertwo_id INT REFERENCES users(user_id) ON DELETE CASCADE,
    PRIMARY KEY (userone_id, usertwo_id)
);

CREATE TABLE IF NOT EXISTS genres (
    genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS genre_films (
    genre_id INT REFERENCES genres(genre_id) ON DELETE CASCADE,
    film_id INT REFERENCES films(film_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS RATINGS (
    mpa_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name VARCHAR(255)
);